name: narayan_farms_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  bloc: ^8.1.0
  customer_relation: ^0.1.0
  delivery_workforce: ^1.0.0
  equatable: ^2.0.5
  firebase_core: ^4.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  go_router: ^14.0.0
  loyalty_levels: ^0.1.0
  narayan_system_core: ^1.1.3
  narayan_system_engine: ^1.2.0
  ordering: ^1.0.0
  supply_inventory: ^1.0.0
  inventory_firebase_adapter: ^1.0.4

dev_dependencies:
  bloc_test: ^9.1.0
  fake_cloud_firestore: ^4.0.1
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  meta: ^1.18.0
  test_api: ^0.7.9
  narayan_system_core:
    path: ../package/narayan_system_core
  narayan_system_engine:
    path: ../package/narayan_system_engine
  supply_inventory:
    path: ../package/supply_inventory
  inventory_firebase_adapter:
    path: ../package/inventory_firebase_adapter
